export const database = [
  {
    totalStaked: 10000,
    date: new Date(),
    APY: 0,
    ended: true,
    earnCoin: 'polygon',
    firstCoin: 'etheruem',
    secondCoin: 'polygon',
  },
  {
    totalStaked: 8529,
    date: new Date(),
    ended: true,
    APY: 12,
    earnCoin: 'polygon',
    firstCoin: 'polygon',
    secondCoin: 'usdt',
  },
  {
    totalStaked: 12224,
    date: new Date(),
    APY: 59,
    ended: false,
    earnCoin: 'etheruem',
    firstCoin: 'etheruem',
    secondCoin: 'usdt',
  },
  {
    totalStaked: 12224,
    date: new Date(),
    APY: 59,
    ended: false,
    earnCoin: 'etheruem',
    firstCoin: 'etheruem',
    secondCoin: 'usdt',
  },
  {
    totalStaked: 12224,
    date: new Date(),
    APY: 59,
    ended: false,
    earnCoin: 'etheruem',
    firstCoin: 'etheruem',
    secondCoin: 'usdt',
  },
  {
    totalStaked: 12224,
    date: new Date(),
    APY: 59,
    ended: false,
    earnCoin: 'etheruem',
    firstCoin: 'etheruem',
    secondCoin: 'usdt',
  },
  {
    totalStaked: 12224,
    date: new Date(),
    APY: 59,
    ended: true,
    earnCoin: 'etheruem',
    firstCoin: 'etheruem',
    secondCoin: 'usdt',
  }
]